### ISSUE TITLE
ImportError: No module named xlrd

### ISSUE THREAD

**Issue by murphyke** [roskakori/cutplace#50]
A coworker complained about this, so I tried it myself.  When I try to pip-install cutplace in a fresh virtual environment, I get "ImportError: No module named xlrd".  I see xlrd specified as a requirement in cutplace's setup.py, however, so I don't understand what's going on.  Apologies if this is some sort of configuration error on my side.  Disclaimer: I'm not a Python guru.

Versions: Python 2.7.2, setuptools 0.6c11, pip 1.3.1 (from running python in the activated environment, importing setuptools and pip and printing them).  Mac OS X 10.7, BTW.

```
pip install -r requirements.txt 
Downloading/unpacking cutplace (from -r requirements.txt (line 1))
  Downloading cutplace-0.7.1.zip (580kB): 580kB downloaded
  Running setup.py egg_info for package cutplace
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/Me/Documents/code/python/test-env/build/cutplace/setup.py", line 33, in <module>
        from cutplace import _cutplace
      File "cutplace/_cutplace.py", line 26, in <module>
        import xlrd
    ImportError: No module named xlrd
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/Me/Documents/code/python/test-env/build/cutplace/setup.py", line 33, in <module>

    from cutplace import _cutplace

  File "cutplace/_cutplace.py", line 26, in <module>

    import xlrd

ImportError: No module named xlrd
```

**Comment by roskakori** [comment]
0.8.x is live, so this is finally fixed for good.
